@startuml

' Activity Classes
class AddSongToPlaylistActivity {
}
class CreatePlaylistActivity {
}
class GetPlaylistActivity {
}
class GetPlaylistSongsActivity {
}
class UpdatePlaylistActivity {
}

' DAO Classes
class AlbumTrackDao {
}
class PlaylistDao {
    getPlaylist(String) : Playlist
}

' Exception Classes
class AlbumTrackNotFoundException {
}
class InvalidAttributeValueException {
}
class PlaylistNotFoundException {
}

' DynamoDB Model Classes
class AlbumTrack {
    -@DynamoDBHashKey asin : String
    -@DynamoDBRangeKey trackNumber : Integer
    -albumName : String
    -songTitle : String
}

class Playlist {
  -@DynamoDBHashKey id : String
  -name : String
  -customerId : String
  -songCount : Integer
  -tags : Set<String>
  -songList : List<AlbumTrack>
}

' Relationships
CreatePlaylistActivity --> PlaylistDao : uses
GetPlaylistActivity --> PlaylistDao : uses
AddSongToPlaylistActivity --> AlbumTrackDao : uses
AddSongToPlaylistActivity --> PlaylistDao : uses
UpdatePlaylistActivity --> PlaylistDao : uses
AlbumTrackDao ..> AlbumTrack : "manages"
PlaylistDao ..> Playlist : "manages"
Playlist "1" *--> "many" AlbumTrack : constains
GetPlaylistSongActivity ..> PlaylistDao

@enduml
